name: Build

env:
  CIBW_BUILD: cp39-* cp310-* # Only build 3.9, 3.10
  CIBW_SKIP: "*i686 *musllinux*" # skip 32-bit and musllinux 

  # Make mac default to universal for arm and x86 support
  CIBW_ARCHS_MACOS: auto universal2
  CIBW_TEST_SKIP: "*universal2:arm64"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: False
      matrix:
        os: [ubuntu-24.04, windows-2024, macos-12] # macosx_x86_64, win_amd64
        # python: ["cp39"] #"cp310", "cp311", "cp312"]  # "pp39"
        # python-version: ["3.9", "3.10"] #"3.8", "pypy3"]

    steps:
      - uses: actions/checkout@v3

      - name: Install Numba
        run: |
          python3 -m pip install pip --upgrade
          python3 -m pip install numba

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.14.1

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
